In [1]:
! pip install rdkit
! pip install gdown

Collecting rdkit
  Downloading rdkit-2025.9.6-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rdkit) (2.0.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from rdkit) (11.3.0)
Downloading rdkit-2025.9.6-cp312-cp312-manylinux_2_28_x86_64.whl (36.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.7/36.7 MB 14.9 MB/s eta 0:00:00
Installing collected packages: rdkit
Successfully installed rdkit-2025.9.6
Requirement already satisfied: gdown in /usr/local/lib/python3.12/dist-packages (5.2.1)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from gdown) (4.13.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from gdown) (3.25.2)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.12/dist-packages (from gdown) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from gdown) (4.67.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2026.2.25)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (1.7.1)

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
import rdkit
import gdown

In [3]:
# 1. Get the URL from the 'Share' button in Drive
url = 'https://drive.google.com/file/d/1uVl3dKKGAvyoW_53R-L4abTns3AQfbmy/view?usp=sharing'

# 2. Download the file
# 'fuzzy=True' allows gdown to extract the File ID automatically from the link
output = 'dataset.csv'
gdown.download(url, output, quiet=False, fuzzy=True)

# 3. Load with Pandas
import pandas as pd
df = pd.read_csv(output)

Downloading...
From: https://drive.google.com/uc?id=1uVl3dKKGAvyoW_53R-L4abTns3AQfbmy
To: /content/dataset.csv
100%|██████████| 525k/525k [00:00<00:00, 88.1MB/s]

In [5]:
df.head(5)

,NR-AR,NR-AR-LBD,NR-AhR,NR-Aromatase,NR-ER,NR-ER-LBD,NR-PPAR-gamma,SR-ARE,SR-ATAD5,SR-HSE,SR-MMP,SR-p53,mol_id,smiles
0,0.0,0.0,1.0,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,TOX3021,CCOc1ccc2nc(S(N)(=O)=O)sc2c1
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0,TOX3020,CCN1C(=O)NC(c2ccccc2)C1=O
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,TOX3024,CC[C@]1(O)CC[C@H]2[C@@H]3CCC4=CCCC[C@@H]4[C@H]...
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0,TOX3027,CCCN(CC)C(CC)C(=O)Nc1c(C)cccc1C
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,TOX20800,CC(O)(P(=O)(O)O)P(=O)(O)O

In [4]:
df.columns

Index(['NR-AR', 'NR-AR-LBD', 'NR-AhR', 'NR-Aromatase', 'NR-ER', 'NR-ER-LBD',
       'NR-PPAR-gamma', 'SR-ARE', 'SR-ATAD5', 'SR-HSE', 'SR-MMP', 'SR-p53',
       'mol_id', 'smiles'],
      dtype='object')

In [ ]:
df.shape

(7831, 14)

In [ ]:
print(f"total number of null values= {df.isnull().sum().sum()}")

total number of null values= 16026

In [ ]:
df.isnull().sum()

NR-AR             566
NR-AR-LBD        1073
NR-AhR           1282
NR-Aromatase     2010
NR-ER            1638
NR-ER-LBD         876
NR-PPAR-gamma    1381
SR-ARE           1999
SR-ATAD5          759
SR-HSE           1364
SR-MMP           2021
SR-p53           1057
mol_id              0
smiles              0
dtype: int64

In [ ]:
targets = [
'NR-AR','NR-AR-LBD','NR-AhR','NR-Aromatase',
'NR-ER','NR-ER-LBD','NR-PPAR-gamma',
'SR-ARE','SR-ATAD5','SR-HSE','SR-MMP','SR-p53'
]

df[targets] = df[targets].fillna(0)

In [ ]:
from rdkit import Chem
from rdkit.Chem import Descriptors

def smiles_to_features(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None

    return [
        Descriptors.MolWt(mol),
        Descriptors.MolLogP(mol),
        Descriptors.NumHDonors(mol),
        Descriptors.NumHAcceptors(mol),
        Descriptors.TPSA(mol),
        Descriptors.NumRotatableBonds(mol)
    ]
features = df['smiles'].apply(smiles_to_features)

# remove invalid rows
df = df[features.notnull()]
features = features[features.notnull()]

X = list(features)

[14:00:39] WARNING: not removing hydrogen atom without neighbors
[14:00:40] Explicit valence for atom # 8 Al, 6, is greater than permitted
[14:00:40] Explicit valence for atom # 3 Al, 6, is greater than permitted
[14:00:40] Explicit valence for atom # 4 Al, 6, is greater than permitted
[14:00:41] Explicit valence for atom # 4 Al, 6, is greater than permitted
[14:00:42] Explicit valence for atom # 9 Al, 6, is greater than permitted
[14:00:42] Explicit valence for atom # 5 Al, 6, is greater than permitted
[14:00:43] Explicit valence for atom # 16 Al, 6, is greater than permitted
[14:00:44] Explicit valence for atom # 20 Al, 6, is greater than permitted

In [ ]:
print(X)

[[258.32399999999996, 1.3424, 1, 5, 82.28, 3], [204.22899999999998, 1.2993999999999999, 1, 2, 49.410000000000004, 2], [288.475, 5.090300000000005, 1, 1, 20.23, 1], [276.42400000000004, 3.7524400000000018, 1, 2, 32.34, 7], [206.027, -0.9922000000000002, 5, 3, 135.29000000000002, 2], [290.444, 4.817200000000005, 0, 4, 36.92, 7], [176.62400000000002, 1.6141, 0, 2, 34.14, 1], [621.9340000000001, 4.625400000000002, 2, 3, 66.76, 4], [152.146, -2.9463000000000004, 5, 5, 101.15, 4], [351.8019999999999, 2.1911000000000005, 0, 4, 80.25999999999999, 12], [663.4300000000004, -3.6478999999999964, 7, 17, 321.0900000000001, 11], [354.1, -1.2181000000000002, 3, 5, 104.55000000000001, 2], [144.21399999999997, 1.8416000000000001, 0, 2, 26.3, 3], [198.21799999999996, 1.2249999999999999, 0, 4, 52.6, 5], [215.70799999999997, 0.24750000000000005, 0, 3, 9.72, 2], [185.202, 1.1321999999999994, 0, 2, 40.129999999999995, 2], [231.37999999999997, 2.4633, 2, 3, 55.480000000000004, 12], [178.235, 1.5636, 0, 2, 33.2, 3], [140.13799999999998, 1.1063999999999998, 2, 3, 49.69, 1], [151.16499999999996, 1.2583, 0, 3, 39.19, 2], [253.279, 1.8801999999999999, 1, 4, 76.49000000000001, 3], [152.149, 0.8046, 2, 2, 57.53, 2], [197.24100000000004, 3.6842000000000015, 1, 3, 50.739999999999995, 2], [292.209, 4.789500000000003, 1, 1, 12.03, 2], [314.21200000000005, 3.775400000000003, 0, 3, 29.54, 2], [314.86, 4.528400000000004, 0, 2, 6.48, 4], [56.064, -0.3881, 1, 1, 20.23, 0], [173.19299999999998, 0.5155000000000001, 2, 3, 80.39, 1], [118.17599999999999, 0.5282, 2, 2, 40.46, 2], [129.24699999999999, 2.1599000000000004, 1, 1, 26.02, 1], [100.16099999999999, 1.6215, 0, 1, 17.07, 2], [86.13399999999999, 1.3755, 0, 1, 17.07, 2], [133.15399999999997, 1.1451, 2, 2, 54.699999999999996, 0], [266.33799999999997, 4.6592, 1, 1, 20.23, 0], [154.21199999999996, 3.353600000000001, 0, 0, 0.0, 1], [219.07099999999997, 2.7447, 2, 1, 41.13, 1], [183.63799999999998, 2.606820000000001, 1, 1, 29.1, 1], [188.33999999999995, 2.0507, 2, 1, 24.06, 6], [172.27199999999993, 1.8858, 2, 1, 41.13, 6], [177.29099999999997, 3.309800000000002, 0, 1, 3.24, 3], [120.19499999999996, 2.5574200000000005, 0, 0, 0.0, 1], [438.6330000000002, 9.3187, 0, 3, 27.69, 20], [356.547, 4.920300000000006, 2, 4, 66.76, 18], [266.381, 4.163100000000004, 0, 3, 43.370000000000005, 10], [502.9200000000002, 7.395680000000005, 1, 5, 71.35, 8], [438.76700000000005, 3.748700000000002, 1, 6, 115.61000000000001, 5], [246.33700000000005, 4.144600000000003, 0, 3, 9.23, 5], [128.215, 2.1152, 1, 1, 20.23, 5], [263.296, 3.641200000000002, 1, 3, 52.32000000000001, 2], [324.4240000000001, 3.1732000000000014, 1, 4, 45.59, 4], [114.14399999999999, 0.9446, 0, 2, 34.14, 3], [123.15899999999999, 0.40336, 1, 3, 59.61, 4], [634.6920000000003, 7.293400000000009, 0, 12, 182.29999999999998, 12], [431.4030000000002, 1.2058, 0, 9, 161.43, 3], [629.6320000000002, 6.436700000000006, 2, 12, 213.17, 8], [356.56, 4.4043000000000045, 0, 4, 6.48, 2], [318.339, 3.201500000000001, 1, 4, 56.84, 9], [136.19400000000002, 1.52982, 1, 1, 20.23, 2], [136.19799999999998, 1.7102799999999998, 0, 2, 25.78, 0], [140.226, 2.1136, 1, 1, 20.23, 0], [122.17099999999999, 1.4018599999999999, 0, 2, 25.78, 0], [178.231, 2.4994000000000005, 0, 2, 26.3, 3], [136.23799999999997, 3.308900000000002, 0, 0, 0.0, 1], [164.086, -0.8590000000000002, 0, 6, 132.4, 0], [153.14100000000002, 0.7592000000000001, 2, 4, 95.18, 1], [149.19299999999998, 1.8793999999999997, 1, 2, 21.259999999999998, 0], [207.012, 2.3972, 2, 2, 57.53, 1], [284.488, 3.9752000000000027, 1, 2, 32.34, 14], [218.362, 3.0659000000000023, 1, 3, 26.3, 8], [263.037, -1.1386000000000003, 3, 4, 120.9, 2], [398.5680000000001, 1.9720999999999997, 3, 9, 78.9, 13], [370.86600000000004, 4.538900000000002, 0, 1, 9.23, 3], [87.81200000000001, 1.4125, 0, 0, 0.0, 0], [156.269, 2.439500000000001, 1, 1, 20.23, 1], [180.24999999999997, 3.857000000000003, 0, 0, 0.0, 2], [192.261, 4.301420000000003, 0, 0, 0.0, 0], [266.25699999999995, -1.1933999999999994, 0, 5, 80.28, 2], [246.19400000000002, -1.6851999999999996, 3, 5, 104.55000000000001, 1], [267.328, 2.8499000000000025, 2, 3, 43.7, 0], [155.197, 0.4213, 0, 3, 29.54, 1], [252.269, 2.8580000000000005, 0, 3, 43.370000000000005, 2], [181.147, 1.60142, 1, 3, 80.44, 2], [181.14699999999996, 1.60142, 1, 3, 80.44, 2], [282.448, 3.5158000000000023, 0, 2, 26.3, 6], [116.20399999999998, 1.9475000000000002, 1, 1, 20.23, 4], [137.11399999999998, -0.24430000000000013, 1, 3, 60.36, 1], [121.13899999999995, 0.7855000000000001, 1, 1, 43.09, 1], [181.23899999999998, 0.6773000000000001, 1, 4, 55.290000000000006, 1], [361.52900000000017, 4.844800000000005, 1, 2, 23.47, 0], [278.221, -3.6124999999999985, 5, 7, 153.88, 5], [333.13800000000003, -0.45710000000000006, 3, 5, 104.55000000000001, 3], [363.50500000000017, 3.308500000000002, 1, 4, 29.950000000000003, 6], [266.34099999999995, 0.45210000000000006, 3, 4, 84.57999999999998, 8], [401.5010000000001, 4.224000000000004, 1, 2, 35.580000000000005, 7], [153.141, 0.7592000000000001, 2, 4, 95.17999999999999, 1], [166.002, -5.992, 0, 0, 0.0, 0], [354.31100000000004, -0.6459000000000001, 6, 8, 164.75, 4], [198.436, 2.7474, 1, 2, 33.120000000000005, 0], [96.12899999999999, 1.3176, 0, 1, 17.07, 2], [270.54999999999995, 3.1752000000000002, 0, 4, 86.28, 2], [161.397, 2.2458, 1, 1, 12.03, 2], [134.562, 0.9543999999999999, 0, 2, 26.3, 3], [275.80100000000004, 2.9716400000000016, 0, 3, 29.54, 5], [525.6420000000002, -0.653199999999996, 3, 12, 172.45999999999998, 10], [333.27400000000006, 1.2690000000000001, 2, 5, 106.50999999999999, 4], [406.2690000000001, 4.665500000000003, 0, 5, 58.400000000000006, 5], [383.5320000000002, 4.452600000000004, 0, 4, 38.769999999999996, 10], [324.44900000000007, 0.612, 2, 6, 106.32999999999998, 3], [383.5170000000001, 0.08690000000000164, 2, 7, 118.79999999999998, 7], [339.4830000000001, 3.361900000000002, 1, 3, 59.22, 8], [326.44, 1.5545, 2, 4, 46.94, 1], [434.50400000000025, 2.2747000000000006, 2, 6, 93.06, 2], [401.42200000000014, 5.242900000000003, 0, 5, 47.03, 5], [174.108, -0.44329999999999964, 3, 3, 111.89999999999999, 4], [1045.7159999999988, 22.611800000000017, 0, 4, 52.6, 40], [180.15599999999998, -3.3772000000000006, 5, 6, 118.22000000000001, 5], [267.306, 1.3016, 1, 4, 72.47, 2], [181.19099999999997, 0.49990000000000007, 3, 4, 69.56, 3], [154.25299999999996, 2.791800000000001, 0, 1, 17.07, 0], [527.5740000000002, 0.46980000000000227, 6, 10, 170.86999999999998, 4], [270.76300000000003, 3.627200000000003, 0, 2, 15.6, 1], [269.35200000000003, 1.9118000000000002, 1, 3, 49.74, 5], [101.12499999999999, -0.07350000000000012, 0, 2, 40.129999999999995, 3], [242.40299999999993, 4.8605000000000045, 0, 2, 26.3, 12], [109.132, 0.2460000000000001, 2, 3, 64.92999999999999, 0], [130.231, 2.3376000000000006, 1, 1, 20.23, 5], [164.27699999999996, 1.2745, 0, 3, 27.69, 5], [166.26399999999995, 3.102000000000002, 0, 1, 17.07, 2], [146.238, -1.916999999999998, 4, 4, 76.1, 7], [329.44000000000005, 3.466880000000002, 2, 4, 76.78, 0], [342.2260000000001, 3.653400000000003, 0, 4, 49.17, 5], [122.17100000000002, 1.1594200000000001, 2, 2, 52.04, 0], [157.301, 2.9564000000000012, 1, 1, 12.03, 8], [90.122, 0.013600000000000112, 1, 2, 29.46, 2], [200.262, 3.943500000000001, 0, 2, 9.23, 0], [57.096, -0.021899999999999975, 1, 1, 21.94, 0], [289.335, 1.6333000000000002, 2, 4, 91.65, 4], [131.131, -0.6210000000000004, 2, 3, 80.39, 4], [416.1350000000001, 6.454800000000002, 0, 2, 27.05, 6], [402.0640000000001, 6.674800000000002, 0, 4, 44.24, 4], [406.482, 3.738000000000002, 3, 5, 75.74000000000001, 10], [114.959, 1.3956, 0, 1, 9.23, 2], [133.191, -0.6623999999999999, 3, 3, 52.489999999999995, 4], [407.5710000000002, 2.1140000000000003, 3, 5, 100.82000000000001, 4], [341.4950000000001, 4.264980000000004, 1, 3, 61.09, 1], [247.03799999999998, -0.8442000000000001, 2, 3, 100.67, 2], [192.214, 1.6895999999999998, 0, 3, 38.83, 3], [109.12799999999997, 1.4876999999999998, 2, 2, 32.26, 1], [134.134, 1.0682, 0, 2, 34.14, 2], [190.45, 0.8832000000000001, 0, 0, 0.0, 0], [293.44900000000007, 3.874500000000003, 0, 4, 66.43, 11], [195.476, 3.7322000000000015, 0, 0, 0.0, 1], [202.24999999999997, 2.2763999999999998, 2, 2, 74.6, 9], [158.24099999999999, 2.5199000000000007, 0, 2, 26.3, 6], [134.175, -0.2354, 2, 3, 49.69, 4], [177.179, 0.2360399999999998, 0, 3, 57.2, 2], [281.29100000000005, 1.2132999999999994, 0, 4, 67.18, 5], [82.106, 0.7181199999999999, 1, 1, 28.68, 0], [332.3650000000001, 2.0915999999999997, 1, 7, 100.33, 5], [359.3970000000001, 2.309300000000001, 3, 5, 73.16000000000001, 2], [466.48700000000014, 2.901600000000001, 3, 6, 133.23999999999998, 9], [410.42300000000023, 1.9508999999999999, 3, 6, 113.96000000000001, 6], [343.4350000000001, 1.4353399999999998, 1, 8, 91.16000000000001, 3], [265.334, 2.734800000000001, 1, 3, 59.3, 4], [483.67400000000026, 6.203220000000006, 3, 6, 92.78000000000002, 7], [284.31899999999996, 1.7812199999999998, 2, 4, 79.51, 2], [440.42900000000026, 0.6345999999999994, 2, 8, 147.02, 4], [285.77400000000006, 4.258500000000003, 0, 2, 12.47, 0], [813.9790000000002, 3.620900000000008, 0, 16, 184.18999999999997, 9], [120.22399999999999, 0.9809999999999999, 0, 2, 18.46, 2], [267.155, 4.249200000000002, 1, 1, 20.23, 2], [290.75, 4.225800000000003, 1, 2, 41.57000000000001, 3], [136.14999999999998, 1.5948, 1, 2, 37.3, 1], [239.485, 3.273900000000001, 1, 1, 37.3, 2], [157.55599999999998, 1.4332, 1, 2, 50.19, 1], [156.269, 3.3260000000000023, 0, 1, 17.07, 8], [148.24900000000002, 3.2925200000000014, 0, 0, 0.0, 0], [173.83499999999998, 1.7337, 0, 0, 0.0, 0], [162.019, 2.5756000000000006, 1, 1, 26.02, 0], [172.268, 3.2117000000000013, 1, 1, 37.3, 8], [251.32599999999996, 3.8954000000000035, 1, 3, 63.370000000000005, 1], [256.40299999999996, -5.807199999999997, 0, 6, 321.4, 0], [223.314, 2.2138, 0, 4, 66.43, 9], [150.13299999999998, 1.1973, 1, 2, 54.370000000000005, 2], [127.014, 2.2426000000000004, 0, 0, 0.0, 2], [136.194, 1.914, 1, 1, 20.23, 1], [85.10600000000001, -0.10360000000000008, 1, 1, 29.1, 0], [161.03099999999995, 3.078800000000001, 0, 0, 0.0, 1], [182.135, 1.8114199999999998, 0, 4, 86.28, 2], [244.34199999999987, 3.891560000000003, 0, 4, 72.3, 2], [170.164, 0.44479999999999986, 0, 4, 52.6, 5], [259.43799999999993, 6.204400000000007, 0, 0, 0.0, 12], [185.14799999999994, 2.7714800000000013, 0, 1, 23.79, 1], [187.036, 2.457700000000001, 0, 1, 9.23, 1], [143.274, 2.566300000000001, 1, 1, 12.03, 7], [300.35400000000004, 4.009200000000003, 0, 4, 36.92, 6], [235.30799999999996, 2.620000000000001, 1, 3, 38.33, 2], [380.55400000000014, 5.296100000000005, 0, 5, 42.010000000000005, 9], [240.263, 0.78162, 0, 4, 67.67, 1], [316.98, 3.773820000000001, 1, 2, 33.120000000000005, 0], [286.23900000000003, 2.2824000000000004, 4, 6, 111.13000000000001, 1], [152.19299999999998, 1.4462, 1, 2, 29.46, 3], [261.08899999999994, 1.884, 1, 2, 41.57, 5], [68.119, 1.7485, 0, 0, 0.0, 1], [60.096000000000004, 0.38710000000000006, 1, 1, 20.23, 0], [213.66400000000002, 3.2969000000000017, 1, 2, 38.33, 2], [179.21900000000002, 2.6435000000000013, 1, 2, 38.33, 2], [162.18799999999996, 2.4484000000000004, 0, 2, 18.46, 1], [143.206, 0.9526999999999999, 0, 2, 40.129999999999995, 5], [361.37300000000005, 1.5439999999999998, 1, 5, 75.00999999999999, 2], [258.273, 2.998820000000001, 0, 4, 52.6, 2], [270.72, 1.8518999999999999, 1, 5, 71.3, 6], [275.39200000000005, 3.886400000000002, 1, 3, 52.32, 3], [232.666, 3.2766000000000015, 1, 2, 37.3, 2], [180.156, -3.2197999999999998, 5, 6, 110.38000000000001, 1], [240.34599999999998, 4.013520000000003, 0, 1, 17.07, 1], [217.35699999999997, 4.601800000000004, 0, 0, 0.0, 6], [967.0210000000009, -5.257999999999982, 14, 23, 374.13000000000005, 12], [483.8700000000006, 12.44599999999998, 0, 0, 0.0, 28], [546.7890000000004, 8.806200000000006, 0, 6, 78.90000000000002, 21], [261.2339999999999, -3.851399999999997, 3, 6, 126.69000000000001, 6], [410.45000000000016, 7.182020000000006, 0, 4, 44.760000000000005, 6], [430.90700000000004, 4.682900000000004, 0, 4, 44.760000000000005, 12], [297.267, -2.6318999999999972, 0, 6, 103.59, 6], [868.8620000000001, 5.2996400000000055, 4, 20, 370.74, 9], [154.12099999999998, 0.7959999999999998, 3, 3, 77.76, 1], [330.208, 1.6896, 2, 8, 160.88, 2], [173.25900000000001, 3.2940000000000014, 1, 1, 12.03, 0], [192.17, 1.51262, 2, 4, 70.67, 0], [129.24699999999996, 1.888, 1, 1, 12.03, 4], [237.7299999999999, 2.897800000000001, 1, 2, 29.1, 2], [344.41100000000006, 1.5022199999999999, 3, 5, 93.81, 10], [268.224, 3.1036, 2, 5, 83.81, 0], [284.267, 2.8798000000000012, 2, 5, 79.9, 2], [254.24099999999999, 2.8712000000000013, 2, 4, 70.67, 1], [270.24, 2.576800000000001, 3, 5, 90.9, 1], [274.272, 2.324500000000001, 4, 5, 97.99000000000001, 4], [336.47900000000004, 4.136700000000004, 0, 2, 23.550000000000004, 6], [254.28500000000003, 3.4011000000000022, 1, 2, 54.37, 5], [384.259, 3.9643000000000033, 1, 5, 64.63, 4], [238.24300000000002, 0.9607999999999993, 2, 4, 104.64000000000001, 5], [231.26099999999997, 3.2459000000000024, 1, 1, 12.03, 4], [288.347, 2.07272, 1, 4, 67.75999999999999, 3], [345.4010000000002, 3.8896000000000033, 1, 5, 56.790000000000006, 8], [253.375, 2.3782000000000005, 2, 6, 62.730000000000004, 4], [330.4680000000001, 3.695900000000003, 1, 3, 54.370000000000005, 2], [464.8580000000002, 0.2649000000000006, 6, 9, 181.61999999999998, 2], [155.19699999999997, 0.8392999999999999, 1, 2, 46.17, 1], [383.4670000000001, 3.0231000000000012, 1, 4, 44.81, 6], [150.232, -1.4322, 4, 2, 76.1, 0], [120.202, -0.44139999999999974, 2, 2, 52.04, 0], [215.237, 1.2067999999999999, 0, 1, 26.099999999999994, 3], [214.21999999999997, 3.264400000000002, 0, 3, 35.53, 2], [251.078, 1.2708, 0, 0, 0.0, 0], [152.182, 1.0154899999999998, 2, 3, 57.36, 0], [200.59, -0.0025, 0, 0, 0.0, 0], [227.396, 3.39037, 3, 1, 61.900000000000006, 11], [261.394, 2.7113000000000005, 0, 4, 19.37, 6], [302.339, 1.5213999999999999, 0, 8, 62.580000000000005, 6], [249.31699999999998, 2.4668, 1, 3, 41.62, 0], [332.5280000000001, 4.985300000000005, 1, 2, 37.3, 1], [423.9130000000001, 1.8602999999999985, 3, 6, 110.05000000000001, 11], [353.827, 2.4881, 2, 3, 83.47, 7], [238.197, 0.7035000000000001, 1, 3, 73.80000000000001, 3], [248.32199999999995, 3.2977000000000025, 0, 3, 35.53, 6], [347.46200000000016, 3.604800000000002, 2, 2, 48.13, 5], [274.26399999999995, 0.6923199999999999, 0, 3, 66.01, 1], [212.679, 4.6464000000000025, 0, 0, 0.0, 0], [226.02599999999995, 2.412700000000001, 0, 0, 8.809999999999999, 3], [336.41000000000014, 4.649100000000004, 1, 2, 28.259999999999998, 3], [283.393, 2.0644, 1, 3, 63.24, 5], [408.7680000000003, 6.742000000000007, 0, 4, 6.48, 12], [419.369, 2.09032, 0, 4, 91.19, 4], [257.13000000000005, 4.755500000000002, 0, 0, 0.0, 0], [217.22400000000002, 1.8679, 0, 4, 47.89, 3], [387.91100000000006, 3.783100000000003, 2, 4, 53.6, 6], [369.4870000000002, 1.2851000000000006, 2, 6, 101.73, 7], [317.4290000000001, 3.238100000000002, 0, 4, 38.77, 4], [273.376, 3.085440000000002, 0, 3, 29.54, 2], [263.281, 1.2980999999999998, 0, 3, 57.2, 1], [324.682, 2.7345000000000006, 0, 7, 83.56, 5], [223.16499999999996, 1.0536999999999999, 1, 5, 73.86, 5], [226.322, 4.288840000000002, 0, 4, 26.28, 3], [682.396, 5.694320000000004, 2, 4, 92.34, 7], [98.145, 1.5416, 0, 1, 17.07, 2], [100.11699999999999, 0.36430000000000007, 0, 2, 26.3, 0], [126.15499999999999, 0.9446, 0, 2, 34.14, 0], [128.12699999999998, 0.7637, 1, 3, 46.53, 0], [138.20999999999998, 3.0123000000000015, 0, 1, 13.14, 4], [134.182, 1.3554, 0, 2, 25.78, 0], [263.33799999999997, 3.086500000000002, 0, 3, 57.2, 4], [341.36800000000005, 4.173320000000002, 1, 6, 102.15, 3], [425.4460000000002, 5.449540000000006, 2, 9, 147.1, 5], [244.20700000000002, -3.1679999999999997, 4, 8, 143.72000000000003, 2], [229.715, 2.1672000000000002, 2, 5, 62.730000000000004, 3], [295.72900000000004, -0.0608999999999999, 2, 5, 118.69, 1], [214.051, 3.2472000000000003, 1, 2, 33.120000000000005, 0], [245.662, 1.1750000000000003, 2, 4, 81.78000000000002, 5], [318.8730000000001, 4.894400000000004, 0, 3, 6.48, 4], [279.49199999999996, 5.0137000000000045, 0, 0, 8.809999999999999, 13], [215.98499999999999, -2.9266, 0, 7, 123.63, 2], [153.332, 2.8109, 0, 1, 17.07, 0], [667.8290000000003, 6.122800000000007, 0, 7, 120.65, 11], [311.592, 4.224800000000003, 0, 3, 35.53, 5], [1701.2060000000006, 4.838100000000016, 25, 46, 777.9800000000005, 21], [255.36100000000002, 3.3542000000000023, 0, 2, 12.47, 6], [150.177, 1.78162, 0, 2, 26.3, 1], [294.442, 4.415700000000004, 0, 2, 6.48, 4], [414.52700000000016, 3.368500000000002, 0, 6, 59.080000000000005, 6], [146.189, 2.2888, 0, 1, 17.07, 2], [142.18300000000002, 0.74091, 2, 2, 48.65, 0], [652.8319999999999, 7.451600000000009, 0, 6, 55.38000000000001, 4], [352.4710000000001, 3.251100000000002, 3, 4, 94.83, 12], [354.48700000000014, 3.0429000000000013, 4, 4, 97.99, 12], [154.253, 2.7441000000000013, 0, 1, 9.23, 0], [170.25199999999998, 1.9452, 1, 2, 29.46, 4], [192.30199999999996, 3.6582000000000026, 0, 1, 17.07, 2], [159.20999999999998, 0.15460000000000013, 1, 3, 46.17, 1], [365.34400000000005, 7.003600000000006, 1, 1, 20.23, 4], [260.12, 2.6042000000000005, 0, 2, 29.54, 1], [74.127, -0.7077, 2, 2, 52.04, 1], [74.12299999999999, 0.7771999999999999, 1, 1, 20.23, 1], [508.80400000000037, 4.256280000000006, 10, 4, 167.58, 19], [75.111, -0.6741000000000001, 2, 2, 46.25, 1], [552.576, -3.1656999999999966, 2, 15, 220.88000000000005, 8], [168.17299999999997, 1.5601, 1, 4, 50.44, 0], [164.20399999999995, 2.1292999999999997, 1, 2, 29.46, 3], [233.228, -1.6370999999999976, 3, 5, 145.87, 6], [253.255, 0.7596, 0, 5, 91.34, 1], [455.9710000000002, 3.4330200000000026, 0, 6, 72.61, 4], [348.39900000000017, 1.1261000000000003, 3, 4, 106.94000000000001, 8], [914.1430000000003, 5.521200000000009, 3, 14, 178.92999999999998, 9], [358.855, 4.291120000000001, 0, 1, 9.23, 1], [648.8480000000003, 6.346400000000008, 2, 8, 91.18, 8], [335.4730000000002, 2.1975999999999996, 1, 3, 56.410000000000004, 6], [422.3960000000001, 1.3082, 4, 8, 166.93999999999997, 2], [603.3100000000002, -1.0248999999999988, 2, 16, 224.55999999999995, 7], [916.1320000000004, 2.9822000000000086, 3, 17, 211.57999999999996, 13], [423.37800000000027, -1.640699999999996, 0, 9, 144.9, 12], [185.26699999999997, 1.4938, 1, 3, 38.33, 4], [241.18999999999994, 1.2326000000000001, 1, 3, 69.39, 2], [194.23399999999995, 1.4644000000000001, 0, 4, 58.86, 4], [294.398, 3.164600000000002, 1, 3, 36.36, 3], [372.43200000000013, 4.208240000000001, 4, 5, 118.94999999999999, 2], [283.283, 3.030800000000002, 3, 4, 90.65, 1], [352.36699999999996, 3.726200000000003, 3, 3, 86.99000000000001, 2], [182.222, -0.2476000000000001, 4, 4, 74.6, 3], [407.50500000000017, 4.945600000000005, 0, 4, 9.72, 4], [168.19599999999997, 0.046620000000000106, 3, 4, 79.37, 2], [201.20299999999997, 0.03219999999999995, 2, 3, 97.46000000000001, 2], [488.67100000000033, 1.4251999999999998, 4, 12, 105.20000000000002, 16], [652.7179999999997, -7.2072000000000145, 13, 13, 358.1899999999999, 9], [383.51700000000017, 2.8560000000000016, 1, 6, 48.300000000000004, 5], [1151.4209999999996, 12.338479999999983, 2, 8, 144.82, 12], [285.391, 2.658400000000001, 0, 4, 28.6, 7], [181.21499999999997, 0.5714999999999999, 0, 2, 33.42, 1], [169.18, 0.08021999999999985, 3, 4, 73.58000000000001, 2], [289.74399999999997, 0.8788000000000005, 3, 4, 101.28999999999999, 2], [324.4240000000001, 3.1732000000000014, 1, 4, 45.59, 4], [257.13000000000005, 4.755500000000002, 0, 0, 0.0, 0], [89.13799999999999, -0.2840000000000001, 2, 2, 46.25, 1], [104.14899999999999, -0.0028000000000000247, 2, 2, 40.46, 2], [120.173, 0.19500000000000006, 0, 2, 34.14, 0], [151.118, -2.0212, 3, 5, 103.83000000000001, 4], [254.27899999999994, -3.070399999999999, 6, 7, 130.61, 10], [284.181, -1.0866999999999987, 0, 10, 160.35000000000002, 12], [121.136, -2.3391999999999995, 4, 4, 86.71000000000001, 3], [265.479, 2.8236000000000008, 0, 3, 51.21, 

In [ ]:
feature_names = [
    "MolWt", "LogP", "HDonors", "HAcceptors", "TPSA", "RotBonds"
]

features_df = pd.DataFrame(features.tolist(), columns=feature_names)
features_df.index = df.index
df = pd.concat([df, features_df], axis=1)

In [ ]:
df.columns

Index(['NR-AR', 'NR-AR-LBD', 'NR-AhR', 'NR-Aromatase', 'NR-ER', 'NR-ER-LBD',
       'NR-PPAR-gamma', 'SR-ARE', 'SR-ATAD5', 'SR-HSE', 'SR-MMP', 'SR-p53',
       'mol_id', 'smiles', 'MolWt', 'LogP', 'HDonors', 'HAcceptors', 'TPSA',
       'RotBonds'],
      dtype='object')

In [ ]:
targets = [
    'NR-AR','NR-AR-LBD','NR-AhR','NR-Aromatase',
    'NR-ER','NR-ER-LBD','NR-PPAR-gamma',
    'SR-ARE','SR-ATAD5','SR-HSE','SR-MMP','SR-p53'
]

y = df[targets]

feature_cols = [
    'MolWt', 'LogP', 'HDonors', 'HAcceptors', 'TPSA', 'RotBonds'
]

X = df[feature_cols]

In [ ]:
X.head()

     MolWt     LogP  HDonors  HAcceptors    TPSA  RotBonds
0  258.324  1.34240        1           5   82.28         3
1  204.229  1.29940        1           2   49.41         2
2  288.475  5.09030        1           1   20.23         1
3  276.424  3.75244        1           2   32.34         7
4  206.027 -0.99220        5           3  135.29         2

In [ ]:
from rdkit import Chem
from rdkit.Chem import rdFingerprintGenerator
import numpy as np

# create generator once
fpgen = rdFingerprintGenerator.GetMorganGenerator(radius=2, fpSize=1024)

def smiles_to_fp(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None

    fp = fpgen.GetFingerprint(mol)
    arr = np.array(fp)
    return arr

fps = df['smiles'].apply(smiles_to_fp)

df = df[fps.notnull()]
fps = fps[fps.notnull()]

fp_df = pd.DataFrame(fps.tolist())
fp_df.index = df.index

df = pd.concat([df, fp_df], axis=1)

[14:02:44] WARNING: not removing hydrogen atom without neighbors

In [ ]:
df.columns

Index([        'NR-AR',     'NR-AR-LBD',        'NR-AhR',  'NR-Aromatase',
               'NR-ER',     'NR-ER-LBD', 'NR-PPAR-gamma',        'SR-ARE',
            'SR-ATAD5',        'SR-HSE',
       ...
                  1014,            1015,            1016,            1017,
                  1018,            1019,            1020,            1021,
                  1022,            1023],
      dtype='object', length=1044)

In [ ]:
targets = [
    'NR-AR','NR-AR-LBD','NR-AhR','NR-Aromatase',
    'NR-ER','NR-ER-LBD','NR-PPAR-gamma',
    'SR-ARE','SR-ATAD5','SR-HSE','SR-MMP','SR-p53'
]

y = df[targets]

X = df.drop(columns=targets + ['mol_id', 'smiles'])
X.columns = X.columns.astype(str)

print("X shape:", X.shape)
print("y shape:", y.shape)
print(X.columns[:10])   # just to inspect

X shape: (7823, 1030)
y shape: (7823, 12)
Index(['MolWt', 'LogP', 'HDonors', 'HAcceptors', 'TPSA', 'RotBonds', '0', '1',
       '2', '3'],
      dtype='object')

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import RandomForestClassifier

model = MultiOutputClassifier(
    RandomForestClassifier(
        n_estimators=200,
        class_weight='balanced_subsample',
        random_state=42,
        n_jobs=-1
    )
)

model.fit(X_train, y_train)

MultiOutputClassifier(estimator=RandomForestClassifier(class_weight='balanced_subsample',
                                                       n_estimators=200,
                                                       n_jobs=-1,
                                                       random_state=42))

In [ ]:
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)

In [ ]:
from sklearn.metrics import roc_auc_score

print("ROC-AUC Scores:\n")

for i, col in enumerate(targets):
    try:
        prob = y_prob[i][:, 1]
        score = roc_auc_score(y_test[col], prob)
        print(f"{col}: {score:.3f}")
    except:
        print(f"{col}: skipped")

ROC-AUC Scores:

NR-AR: 0.798
NR-AR-LBD: 0.853
NR-AhR: 0.873
NR-Aromatase: 0.756
NR-ER: 0.758
NR-ER-LBD: 0.800
NR-PPAR-gamma: 0.887
SR-ARE: 0.790
SR-ATAD5: 0.867
SR-HSE: 0.809
SR-MMP: 0.857
SR-p53: 0.861

In [ ]:
print(X_test)

        MolWt     LogP  HDonors  HAcceptors    TPSA  RotBonds  0  1  2  3  \
1142   75.067 -0.97030        2           2   63.32         1  0  0  0  0
4262  404.410  2.87950        3           6   91.68         9  0  1  0  0
2167  318.373  1.62290        0           4   66.92         5  0  0  0  0
1678  397.491  1.95120        2           5   89.82         8  0  1  0  1
3537  226.276  1.38940        2           2   78.76         4  0  1  0  0
...       ...      ...      ...         ...     ...       ... .. .. .. ..
3919  602.641 -0.45420        9          12  242.98        10  0  1  0  0
4323  118.132  1.17940        0           3   35.53         2  0  0  0  0
7354  338.521 -0.70450        2           3   49.69         3  0  0  0  0
5763  125.127  0.62928        0           3   50.09         3  0  0  0  0
5013  622.539  0.65020        5          11  228.51        12  0  0  0  0

      ...  1014  1015  1016  1017  1018  1019  1020  1021  1022  1023
1142  ...     0     0     0     0     0     0     0     0     0     0
4262  ...     0     0     0     0     0     0     0     0     0     0
2167  ...     0     0     0     1     0     1     0     0     0     0
1678  ...     0     0     0     0     0     1     0     0     0     0
3537  ...     0     0     0     0     0     0     0     0     0     0
...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
3919  ...     0     0     0     0     0     1     0     0     0     0
4323  ...     0     0     0     0     0     0     0     0     0     0
7354  ...     0     0     0     0     0     0     0     0     0     0
5763  ...     0     0     0     0     0     0     0     0     0     0
5013  ...     0     0     0     0     0     1     0     0     0     0

[1565 rows x 1030 columns]

### prediction pipeline

In [ ]:
import pandas as pd
import numpy as np
from rdkit import Chem
from rdkit.Chem import Descriptors, rdFingerprintGenerator
loop
# fingerprint generator (same as before)
fpgen = rdFingerprintGenerator.GetMorganGenerator(radius=2, fpSize=1024)

def smiles_to_features(smiles):
    mol = Chem.MolFromSmiles(smiles)

    if mol is None:
        raise ValueError("Invalid SMILES string")

    # Descriptors
    desc = [
        Descriptors.MolWt(mol),
        Descriptors.MolLogP(mol),
        Descriptors.NumHDonors(mol),
        Descriptors.NumHAcceptors(mol),
        Descriptors.TPSA(mol),
        Descriptors.NumRotatableBonds(mol)
    ]

    # Fingerprint
    fp = fpgen.GetFingerprint(mol)
    fp_array = np.array(fp)

    # Combine
    features = np.concatenate([desc, fp_array])

    return features

def prepare_input(smiles, X_columns):
    features = smiles_to_features(smiles)

    # convert to DataFrame
    input_df = pd.DataFrame([features], columns=X_columns)

    return input_df

def predict_smiles(smiles, model, X_columns, targets):

    input_df = prepare_input(smiles, X_columns)

    preds = model.predict(input_df)
    probs = model.predict_proba(input_df)

    result = {}

    for i, col in enumerate(targets):
        result[col] = {
            "prediction": int(preds[0][i]),
            "probability": float(probs[i][0][1])
        }

    return result

X_columns = X.columns

In [ ]:
smiles = "C1=CC=C(C=C1)O"

output = predict_smiles(smiles, model, X_columns, targets)

print(output)

{'NR-AR': {'prediction': 0, 'probability': 0.0}, 'NR-AR-LBD': {'prediction': 0, 'probability': 0.005}, 'NR-AhR': {'prediction': 0, 'probability': 0.04}, 'NR-Aromatase': {'prediction': 0, 'probability': 0.005}, 'NR-ER': {'prediction': 0, 'probability': 0.045}, 'NR-ER-LBD': {'prediction': 0, 'probability': 0.075}, 'NR-PPAR-gamma': {'prediction': 0, 'probability': 0.005}, 'SR-ARE': {'prediction': 0, 'probability': 0.06}, 'SR-ATAD5': {'prediction': 0, 'probability': 0.03}, 'SR-HSE': {'prediction': 0, 'probability': 0.01}, 'SR-MMP': {'prediction': 0, 'probability': 0.075}, 'SR-p53': {'prediction': 0, 'probability': 0.01}}